### ISSUE TITLE
Lovelace UI  empty page

### ISSUE THREAD

**Issue by najjadasm** [joBr99/nspanel-lovelace-ui#33]
NSPANEL Lovelace UI doesn't display entries only display the weather and media player 

 the climate not contr
![Uploading 16471800282068491039455570244296.jpg…]()
olled from the NSPANEL

**Comment by joBr99** [comment]
Hey, 
please add your apps.yaml config and the AppDaemon Log to the issue.

**Comment by najjadasm** [comment]
![Uploading Screenshot_20220313-173421_Home Assistant.jpg…]()

**Comment by najjadasm** [comment]
![Screenshot_20220313-173421_Home Assistant](https://user-images.githubusercontent.com/60378456/158064592-f3b8bbf9-e7cd-4052-9cc1-62c31dfde2cc.jpg)

**Comment by najjadasm** [comment]
2022-03-13 17:34:55.749308 INFO nspanel: Setting dim value to {'time': '7:00:00', 'value': 10}

Log Entry

2022-03-13 17:34:55.390821 INFO AppDaemon: Initializing app nspanel using class NsPanelLovelaceUIManager from module nspanel-lovelace-ui

Log Entry

2022-03-13 17:34:55.354004 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py

Log Entry

2022-03-13 17:34:55.261096 INFO AppDaemon: Adding /config/appdaemon/apps/nspanel-lovelace-ui to module import path

Log Entry

2022-03-13 17:34:53.229684 INFO AppDaemon: App 'nspanel' added

Log Entry

2022-03-13 17:34:38.757297 INFO AppDaemon: Terminating nspanel

Log Entry

2022-03-13 17:34:38.753854 INFO AppDaemon: Removing module /config/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py

Log Entry

2022-03-13 17:34:01.544563 INFO nspanel: Setting dim value to {'time': '7:00:00', 'value': 10}

Log Entry

2022-03-13 17:34:01.512027 INFO AppDaemon: Initializing app nspanel using class NsPanelLovelaceUIManager from module nspanel-lovelace-ui

Log Entry

2022-03-13 17:34:01.510771 INFO AppDaemon: Terminating nspanel

Log Entry

2022-03-13 17:34:01.490050 INFO AppDaemon: App 'nspanel' changed

Log Entry

2022-03-13 17:31:40.457400 INFO nspanel: Setting dim value to {'time': '7:00:00', 'value': 10}

Log Entry

2022-03-13 17:31:40.416794 INFO AppDaemon: Initializing app nspanel using class NsPanelLovelaceUIManager from module nspanel-lovelace-ui

Log Entry

2022-03-13 17:31:40.415985 INFO AppDaemon: Terminating nspanel

Log Entry

2022-03-13 17:31:40.396343 INFO AppDaemon: App 'nspanel' changed

Log Entry

2022-03-13 17:26:27.904061 INFO nspanel: Setting dim value to {'time': '7:00:00', 'value': 10}

Log Entry

2022-03-13 17:26:27.277071 INFO AppDaemon: Initializing app nspanel using class NsPanelLovelaceUIManager from module nspanel-lovelace-ui

Log Entry

2022-03-13 17:26:27.252631 INFO AppDaemon: Terminating nspanel

Log Entry

2022-03-13 16:06:45.546275 INFO nspanel: Setting dim value to {'time': '7:00:00', 'value': 10

**Comment by joBr99** [comment]
So far the configuration looks good, are there error messages in the appdaemon log while navigating through the pages?

Also please update your appdaemon app to v1.2.1 with this release there will be error messages on the screen itself in case an entitiy isn't found.

**Comment by najjadasm** [comment]
no there isno error messages on nspanel

**Comment by joBr99** [comment]
did you upgrade the appdaemon app to the latest release?

**Comment by joBr99** [comment]
please add `log_level: "debug"` to your apps.yaml and send me the output while navigating though the pages
---
```yaml
nspanel-kueche:
  module: nspanel-lovelace-ui
  class: NsPanelLovelaceUIManager
  log_level: DEBUG
  config:
```

**Comment by najjadasm** [comment]
I have updated to last ver

please see below

<html>
<body>


2022-03-13 19:06:52.229981 DEBUG nspanel: get state: sensor.water_tank_level, {} from nspanel
--
2022-03-13 19:06:52.228190 DEBUG nspanel: Generating item command for sensor.water_tank_level with type sensor
2022-03-13 19:06:52.227127 DEBUG nspanel: State change on current page for sensor.water_tank_level
2022-03-13 19:06:52.225691 DEBUG nspanel: Got state_callback from sensor.water_tank_level
2022-03-13 19:06:45.603443 DEBUG nspanel: get state: sensor.water_tank_level, {} from nspanel
2022-03-13 19:06:45.600113 DEBUG nspanel: Generating item command for sensor.water_tank_level with type sensor
2022-03-13 19:06:45.596459 DEBUG nspanel: call_service: mqtt/publish, {'topic': 'cmnd/ns/CustomSend', 'payload': 'entityUpdHeading,Test Page 1'}
2022-03-13 19:06:45.594657 DEBUG nspanel: Send Message from Tasmota: entityUpdHeading,Test Page 1
2022-03-13 19:06:45.590076 DEBUG nspanel: call_service: mqtt/publish, {'topic': 'cmnd/ns/CustomSend', 'payload': 'pageType,cardEntities'}
2022-03-13 19:06:45.588710 DEBUG nspanel: Send Message from Tasmota: pageType,cardEntities
2022-03-13 19:06:45.587536 DEBUG nspanel: Generating page commands for page 0 with type cardEntities
2022-03-13 19:06:45.586476 DEBUG nspanel: Received pageOpen command, raw page: 9, calc page: 0
2022-03-13 19:06:45.585467 DEBUG nspanel: Received Message from Tasmota: event,pageOpen,9
2022-03-13 19:06:45.384509 DEBUG nspanel: get state: sensor.water_tank_level, {} from nspanel
2022-03-13 19:06:45.382497 DEBUG nspanel: Generating item command for sensor.water_tank_level with type sensor
2022-03-13 19:06:45.380417 DEBUG nspanel: call_service: mqtt/publish, {'topic': 'cmnd/ns/CustomSend', 'payload': 'entityUpdHeading,Test Page 1'}
2022-03-13 19:06:45.379683 DEBUG nspanel: Send Message from Tasmota: entityUpdHeading,Test Page 1
2022-03-13 19:06:45.378154 DEBUG nspanel: call_service: mqtt/publish, {'topic': 'cmnd/ns/CustomSend', 'payload': 'pageType,cardEntities'}
2022-03-13 19:06:45.377492 DEBUG nspanel: Send Message from Tasmota: pageType,cardEntities
2022-03-13 19:06:45.376816 DEBUG nspanel: Generating page commands for page 0 with type cardEntities
2022-03-13 19:06:45.376248 DEBUG nspanel: Received pageOpen command, raw page: 9, calc page: 0
2022-03-13 19:06:45.375373 DEBUG nspanel: Received Message from Tasmota: event,pageOpen,9
2022-03-13 19:06:44.398598 DEBUG nspanel: call_service: mqtt/publish, {'topic': 'cmnd/ns/CustomSend', 'payload': 'entityUpd,\|media_player.tv_2\|TV\|0\|\|\|61\|9'}
2022-03-13 19:06:44.398269 DEBUG nspanel: Send Message from Tasmota: entityUpd,\|media_player.tv_2\|TV\|0\|\|\|61\|9
2022-03-13 19:06:44.396068 DEBUG nspanel: get state: media_player.tv_2, {} from nspanel
2022-03-13 19:06:44.394583 DEBUG nspanel: State change on current page for media_player.tv_2
2022-03-13 19:06:44.393453 DEBUG nspanel: Got state_callback from media_player.tv_2
2022-03-13 19:06:44.297152 DEBUG nspanel: call_service: media_player/volume_set, {'volume_level': 0.61, 'entity_id': 'media_player.tv_2'}
2022-03-13 19:06:44.296073 DEBUG nspanel: Received Message from Tasmota: event,buttonPress,8,TV,media_player.tv_2,1,volumeSlider,61
2022-03-13 19:06:44.289849 DEBUG nspanel: call_service: mqtt/publish, {'topic': 'cmnd/ns/CustomSend', 'payload': 'entityUpd,\|media_player.tv_2\|TV\|0\|\|\|62\|9'}
2022-03-13 19:06:44.289338 DEBUG nspanel: Send Message from Tasmota: entityUpd,\|media_player.tv_2\|TV\|0\|\|\|62\|9
2022-03-13 19:06:44.286704 DEBUG nspanel: get state: media_player.tv_2, {} from nspanel
2022-03-13 19:06:44.284544 DEBUG nspanel: call_service: mqtt/publish, {'topic': 'cmnd/ns/CustomSend', 'payload': 'pageType,cardMedia'}
2022-03-13 19:06:44.284207 DEBUG nspanel: Send Message from Tasmota: pageType,cardMedia
2022-03-13 19:06:44.283745 DEBUG nspanel: Generating page commands for page 2 with type cardMedia
2022-03-13 19:06:44.280111 DEBUG nspanel: Received pageOpen command, raw page: 8, calc page: 2
2022-03-13 19:06:44.279203 DEBUG nspanel: Received Message from Tasmota: event,pageOpen,8
2022-03-13 19:06:43.848216 DEBUG nspanel: call_service: mqtt/publish, {'topic': 'cmnd/ns/CustomSend', 'payload': 'entityUpd,\|media_player.tv_2\|TV\|0\|\|\|62\|9'}
2022-03-13 19:06:43.847804 DEBUG nspanel: Send Message from Tasmota: entityUpd,\|media_player.tv_2\|TV\|0\|\|\|62\|9
2022-03-13 19:06:43.844473 DEBUG nspanel: get state: media_player.tv_2, {} from nspanel
2022-03-13 19:06:43.842794 DEBUG nspanel: call_service: mqtt/publish, {'topic': 'cmnd/ns/CustomSend', 'payload': 'pageType,cardMedia'}
2022-03-13 19:06:43.842453 DEBUG nspanel: Send Message from Tasmota: pageType,cardMedia
2022-03-13 19:06:43.841288 DEBUG nspanel: Generating page commands for page 2 with type cardMedia
2022-03-13 19:06:43.840337 DEBUG nspanel: Received pageOpen command, raw page: 8, calc page: 2
2022-03-13 19:06:43.839813 DEBUG nspanel: Received Message from Tasmota: event,pageOpen,8
2022-03-13 19:06:41.285818 DEBUG nspanel: get state: sensor.water_tank_level, {} from nspanel
2022-03-13 19:06:41.282007 DEBUG nspanel: Generating item command for sensor.water_tank_level with type sensor
2022-03-13 19:06:41.281051 DEBUG nspanel: call_service: mqtt/publish, {'topic': 'cmnd/ns/CustomSend', 'payload': 'entityUpdHeading,Test Page 1'}
2022-03-13 19:06:41.280673 DEBUG nspanel: Send Message from Tasmota: entityUpdHeading,Test Page 1
2022-03-13 19:06:41.278978 DEBUG nspanel: call_service: mqtt/publish, {'topic': 'cmnd/ns/CustomSend', 'payload': 'pageType,cardEntities'}
2022-03-13 19:06:41.278473 DEBUG nspanel: Send Message from Tasmota: pageType,cardEntities
2022-03-13 19:06:41.277586 DEBUG nspanel: Generating page commands for page 0 with type cardEntities
2022-03-13 19:06:41.276672 DEBUG nspanel: Received pageOpen command, raw page: 9, calc page: 0
2022-03-13 19:06:41.274939 DEBUG nspanel: Received Message from Tasmota: event,pageOpen,9
2022-03-13 19:06:40.837090 DEBUG nspanel: get state: sensor.water_tank_level, {} from nspanel
2022-03-13 19:06:40.835971 DEBUG nspanel: Generating item command for sensor.water_tank_level with type sensor
2022-03-13 19:06:40.834393 DEBUG nspanel: call_service: mqtt/publish, {'topic': 'cmnd/ns/CustomSend', 'payload': 'entityUpdHeading,Test Page 1'}
2022-03-13 19:06:40.833917 DEBUG nspanel: Send Message from Tasmota: entityUpdHeading,Test Page 1
2022-03-13 19:06:40.832060 DEBUG nspanel: call_service: mqtt/publish, {'topic': 'cmnd/ns/CustomSend', 'payload': 'pageType,cardEntities'}
2022-03-13 19:06:40.831609 DEBUG nspanel: Send Message from Tasmota: pageType,cardEntities
2022-03-13 19:06:40.831095 DEBUG nspanel: Generating page commands for page 0 with type cardEntities
2022-03-13 19:06:40.830381 DEBUG nspanel: Received pageOpen command, raw page: 9, calc page: 0
2022-03-13 19:06:40.828782 DEBUG nspanel: Received Message from Tasmota: event,pageOpen,9
2022-03-13 19:06:39.979678 DEBUG nspanel: get state: climate.living_room_ac, {} from nspanel
2022-03-13 19:06:39.977334 DEBUG nspanel: call_service: mqtt/publish, {'topic': 'cmnd/ns/CustomSend', 'payload': 'pageType,cardThermo'}
2022-03-13 19:06:39.976877 DEBUG nspanel: Send Message from Tasmota: pageType,cardThermo
2022-03-13 19:06:39.976389 DEBUG nspanel: Generating page commands for page 1 with type cardThermo
2022-03-13 19:06:39.975980 DEBUG nspanel: Received pageOpen command, raw page: 10, calc page: 1
2022-03-13 19:06:39.975467 DEBUG nspanel: Received Message from Tasmota: event,pageOpen,10
2022-03-13 19:06:39.829522 DEBUG nspanel: get state: climate.living_room_ac, {} from nspanel
2022-03-13 19:06:39.827731 DEBUG nspanel: call_service: mqtt/publish, {'topic': 'cmnd/ns/CustomSend', 'payload': 'pageType,cardThermo'}
2022-03-13 19:06:39.827166 DEBUG nspanel: Send Message from Tasmota: pageType,cardThermo
2022-03-13 19:06:39.826735 DEBUG nspanel: Generating page commands for page 1 with type cardThermo
2022-03-13 19:06:39.826303 DEBUG nspanel: Received pageOpen command, raw page: 10, calc page: 1
2022-03-13 19:06:39.825921 DEBUG nspanel: Received Message from Tasmota: event,pageOpen,10
2022-03-13 19:06:37.235789 DEBUG nspanel: get state: sensor.water_tank_level, {} from nspanel
2022-03-13 19:06:37.233297 DEBUG nspanel: Generating item command for sensor.water_tank_level with type sensor
2022-03-13 19:06:37.231889 DEBUG nspanel: State change on current page for sensor.water_tank_level
2022-03-13 19:06:37.230882 DEBUG nspanel: Got state_callback from sensor.water_tank_level
2022-03-13 19:06:22.226272 DEBUG nspanel: get state: sensor.water_tank_level, {} from nspanel


</body>
</html>

**Comment by najjadasm** [comment]
![16471883139687342675981615205218](https://user-images.githubusercontent.com/60378456/158068922-a35c71fd-ba8f-4e4b-abab-a1635bf9cada.jpg)
![16471883317383737397109524949219](https://user-images.githubusercontent.com/60378456/158068933-af5786ce-1232-4a33-b8ab-e9b50ad89e7b.jpg)

the pages has the current entity_id not showing up

**Comment by joBr99** [comment]
![image](https://user-images.githubusercontent.com/29555657/158069049-eda4a419-e9c3-47bf-90e5-bbe561f38c70.png)

does the `sensor.water_tank_level` exist in the homeassistant developer console?

**Comment by najjadasm** [comment]
![Screenshot_20220313-192446_Home Assistant](https://user-images.githubusercontent.com/60378456/158069168-b2d8ce7d-fe0d-4a33-88f6-dcf39ceb0c18.jpg)

**Comment by joBr99** [comment]
scoll a bit down, how looks this section

![image](https://user-images.githubusercontent.com/29555657/158069290-d3609c90-ee49-4127-990c-44f00f7682fb.png)

**Comment by najjadasm** [comment]
![Screenshot_20220313-192953_Home Assistant](https://user-images.githubusercontent.com/60378456/158069356-77ea8f35-3aee-4116-a2d8-92b9bd784c1b.jpg)

**Comment by joBr99** [comment]
yeah search for your water tank level sensor, would like to see the blue id for the water level sensor

**Comment by najjadasm** [comment]
![Screenshot_20220313-193333_Home Assistant](https://user-images.githubusercontent.com/60378456/158069512-2044ea6c-c1ac-4e73-afff-c716a326a091.jpg)

**Comment by joBr99** [comment]
ok, that's also looking good :/

**Comment by joBr99** [comment]
Your configuration and mqtt lookgs good, the only thing that's possible ist that your connection to homeassistant doesn't work.

**Comment by najjadasm** [comment]
how can I make sure the connection is fine?

**Comment by joBr99** [comment]
It's only a random guess, but you should see in your appdaemon log the following messages after restarting it. (comment/disable the debug log, so you don't get flooded by log messages)

```
2022-03-13 17:53:30.413530 INFO AppDaemon: Loading Plugin MQTT using class MqttPlugin from module mqttplugin
2022-03-13 17:53:30.416678 INFO MQTT: MQTT Plugin Initializing
2022-03-13 17:53:30.416776 INFO MQTT: Using 'appdaemon/status' as Will Topic
2022-03-13 17:53:30.416847 INFO MQTT: Using 'appdaemon/status' as Birth Topic
2022-03-13 17:53:30.417107 INFO AppDaemon: Initializing HTTP
2022-03-13 17:53:30.417280 INFO AppDaemon: Using 'ws' for event stream
2022-03-13 17:53:30.418994 INFO AppDaemon: Starting API
2022-03-13 17:53:30.420769 INFO AppDaemon: Starting Admin Interface
2022-03-13 17:53:30.420936 INFO AppDaemon: Starting Dashboards
**2022-03-13 17:53:30.430323 INFO HASS: Connected to Home Assistant 2022.3.4**
2022-03-13 17:53:30.455668 INFO AppDaemon: App 'nspanel-kueche' added
```

**Comment by najjadasm** [comment]
![Screenshot_20220313-200059_Home Assistant](https://user-images.githubusercontent.com/60378456/158070575-628c1895-ab83-4979-bfe9-cae6b5b24568.jpg)

**Comment by joBr99** [comment]
how does your appdaemon log look like after starting the plugin? mine looks like this:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: AppDaemon 4
 Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 0.8.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 7.4  (amd64 / qemux86-64)
 Home Assistant Core: 2022.3.4
 Home Assistant Supervisor: 2022.03.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] appdaemon.sh: executing... 
[cont-init.d] appdaemon.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[17:53:29] INFO: Starting AppDaemon...
2022-03-13 17:53:30.383958 INFO AppDaemon: AppDaemon Version 4.2.1 starting
2022-03-13 17:53:30.384077 INFO AppDaemon: Python version is 3.9.7
2022-03-13 17:53:30.384170 INFO AppDaemon: Configuration read from: /config/appdaemon/appdaemon.yaml
2022-03-13 17:53:30.384248 INFO AppDaemon: Added log: AppDaemon
2022-03-13 17:53:30.384325 INFO AppDaemon: Added log: Error
2022-03-13 17:53:30.384398 INFO AppDaemon: Added log: Access
2022-03-13 17:53:30.384504 INFO AppDaemon: Added log: Diag
2022-03-13 17:53:30.384766 INFO AppDaemon: Running AD using uvloop
2022-03-13 17:53:30.395852 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2022-03-13 17:53:30.413288 INFO HASS: HASS Plugin Initializing
2022-03-13 17:53:30.413402 INFO HASS: HASS Plugin initialization complete
2022-03-13 17:53:30.413530 INFO AppDaemon: Loading Plugin MQTT using class MqttPlugin from module mqttplugin
2022-03-13 17:53:30.416678 INFO MQTT: MQTT Plugin Initializing
2022-03-13 17:53:30.416776 INFO MQTT: Using 'appdaemon/status' as Will Topic
2022-03-13 17:53:30.416847 INFO MQTT: Using 'appdaemon/status' as Birth Topic
2022-03-13 17:53:30.417107 INFO AppDaemon: Initializing HTTP
2022-03-13 17:53:30.417280 INFO AppDaemon: Using 'ws' for event stream
2022-03-13 17:53:30.418994 INFO AppDaemon: Starting API
2022-03-13 17:53:30.420769 INFO AppDaemon: Starting Admin Interface
2022-03-13 17:53:30.420936 INFO AppDaemon: Starting Dashboards
2022-03-13 17:53:30.430323 INFO HASS: Connected to Home Assistant 2022.3.4
```

**Comment by najjadasm** [comment]
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: AppDaemon 4
 Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 0.8.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 7.4  (amd64 / qemux86-64)
 Home Assistant Core: 2022.3.4
 Home Assistant Supervisor: 2022.03.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] appdaemon.sh: executing... 
Looking in links: https://wheels.home-assistant.io/alpine-3.14/amd64/
Requirement already satisfied: voluptuous in /usr/lib/python3.9/site-packages (0.12.2)
Looking in links: https://wheels.home-assistant.io/alpine-3.14/amd64/
Collecting datetime
  Downloading https://wheels.home-assistant.io/alpine-3.14/amd64/DateTime-4.4-py2.py3-none-any.whl (51 kB)
Collecting zope.interface
  Downloading https://wheels.home-assistant.io/alpine-3.14/amd64/zope.interface-5.4.0-cp39-none-any.whl (210 kB)
Requirement already satisfied: pytz in /usr/lib/python3.9/site-packages (from datetime) (2021.3)
Requirement already satisfied: setuptools in /usr/lib/python3.9/site-packages (from zope.interface->datetime) (52.0.0)
Installing collected packages: zope.interface, datetime
Successfully installed datetime-4.4 zope.interface-5.4.0
[cont-init.d] appdaemon.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[20:08:23] INFO: Starting AppDaemon...

**Comment by joBr99** [comment]
Do you see the hass plugin connected in AppDeamon's Webinterface?

http://192.168.100.44:5050/aui/index.html#/state?tab=plugins

**Comment by najjadasm** [comment]
plugin.HASS	active	
plugin.MQTT	active

**Comment by joBr99** [comment]
can you update to the current development version of the repo in hacs?, fixed something that could be releated

**Comment by joBr99** [comment]
just select main as version
![image](https://user-images.githubusercontent.com/29555657/158071964-4aa16236-1afa-4539-9f20-4877b896cd87.png)

**Comment by najjadasm** [comment]
![16471937227777636187158577141923](https://user-images.githubusercontent.com/60378456/158072415-0b9f3239-6fc7-42e1-98f7-693d429f9c41.jpg)

now working fain

but the climate still freeze not responding

**Comment by najjadasm** [comment]
![16471938130127187362745678238849](https://user-images.githubusercontent.com/60378456/158072470-e73a313f-bdea-44cc-b486-08599b8ffe11.jpg)

not working

**Comment by joBr99** [comment]
can you send me the state attributes of that entity?

**Comment by najjadasm** [comment]
![Screenshot_20220313-205553_Home Assistant](https://user-images.githubusercontent.com/60378456/158072657-f8be5460-f468-48eb-b830-6b562f98f81d.jpg)

**Comment by joBr99** [comment]
please update and try again

**Comment by najjadasm** [comment]
which update do you mean

**Comment by joBr99** [comment]
if you are already on the development version you should be able to press update information

![image](https://user-images.githubusercontent.com/29555657/158073639-f16b4095-3614-483c-bfde-aeda812c73da.png)

**Comment by najjadasm** [comment]
the issue for the Ul back again after the update 
the climate still freeze also

**Comment by najjadasm** [comment]
![Screenshot_20220313-223011_WhatsApp](https://user-images.githubusercontent.com/60378456/158075861-13c88729-d7fe-413b-9b8c-da8f4e5445eb.jpg)

**Comment by joBr99** [comment]
Are you sure that you are on the most recent version? I released it as v1.2.2 just in case.

**Comment by najjadasm** [comment]
I have updated to 1.2.2 and Ul back to normal 
the remaining the climate still freeze

**Comment by joBr99** [comment]
sadly I don't have the logs from generating the page, there should be a big python error message sourounded by WARNING there's something wrong during page generation

**Comment by najjadasm** [comment]
2022-03-13 22:54:19.073932 WARNING nspanel: ------------------------------------------------------------2022-03-13 22:54:19.073771 WARNING nspanel: Worker Ags: {'id': '400479a31dde47ada4083d44676cb3b9', 'name': 'nspanel', 'objectid': '6a834cd76f0b46e5a7230a6f3f4de81d', 'type': 'state', 'function': <bound method NsPanelLovelaceUI.state_change_callback of <nspanel-lovelace-ui.NsPanelLovelaceUI object at 0x7f5337b2edc0>>, 'attribute': 'all', 'entity': 'climate.living_room_ac', 'new_state': {'entity_id': 'climate.living_room_ac', 'state': 'on', 'attributes': {'hvac_modes': ['off', 'cool', 'dry', 'fan_only'], 'min_temp': 18.0, 'max_temp': 30.0, 'target_temp_step': 1.0, 'fan_modes': ['auto', 'low', 'medium', 'high'], 'current_temperature': 23.6, 'temperature': 23, 'fan_mode': 'auto', 'last_on_operation': 'cool', 'device_code': 1318, 'manufacturer': 'Fujitsu', 'supported_models': ['AR-AB5'], 'supported_controller': 'Broadlink', 'commands_encoding': 'Base64', 'friendly_name': 'Living Room AC', 'supported_features': 9}, 'last_changed': '2022-03-13T19:27:10.710819+00:00', 'last_updated': '2022-03-13T19:54:19.035252+00:00', 'context': {'id': 'dd7e44a19a3483fb81ddca34aaabad38', 'parent_id': None, 'user_id': None}}, 'old_state': {'entity_id': 'climate.living_room_ac', 'state': 'on', 'attributes': {'hvac_modes': ['off', 'cool', 'dry', 'fan_only'], 'min_temp': 18.0, 'max_temp': 30.0, 'target_temp_step': 1.0, 'fan_modes': ['auto', 'low', 'medium', 'high'], 'current_temperature': 23.7, 'temperature': 23, 'fan_mode': 'auto', 'last_on_operation': 'cool', 'device_code': 1318, 'manufacturer': 'Fujitsu', 'supported_models': ['AR-AB5'], 'supported_controller': 'Broadlink', 'commands_encoding': 'Base64', 'friendly_name': 'Living Room AC', 'supported_features': 9}, 'last_changed': '2022-03-13T19:27:10.710819+00:00', 'last_updated': '2022-03-13T19:53:19.034702+00:00', 'context': {'id': 'cf4fe8ae0039a96f375e17465b240740', 'parent_id': None, 'user_id': None}}, 'pin_app': True, 'pin_thread': 5, 'kwargs': {'attribute': 'all', '__thread_id': 'thread-5'}}2022-03-13 22:54:19.073505 WARNING nspanel: Unexpected error in worker for App nspanel:2022-03-13 22:54:19.073369 WARNING nspanel: ------------------------------------------------------------2022-03-13 22:53:19.081566 WARNING nspanel: ------------------------------------------------------------AttributeError: 'AttrDict' object has no attribute 'hvac_action'status = entity.attributes.hvac_actionFile "/config/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py", line 373, in generate_thermo_pageself.send_mqtt_msg(self.generate_thermo_page(entity))File "/config/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py", line 303, in state_change_callbackfuncref(File "/usr/lib/python3.9/site-packages/appdaemon/threading.py", line 917, in worker2022-03-13 22:53:19.081367 WARNING nspanel: Traceback (most recent call last):

**Comment by joBr99** [comment]
your appdaemon app cannot be the latest, this error says that `'hvac_action'status = entity.attributes.hvac_action` is on line 373 but it's on line 380 in the current version in the latest version (it was in line 373 on v1.2.1)

attribute 'hvac_action'status = entity.attributes.hvac_actionFile "/config/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py", line 373

**Comment by Dattel** [comment]
maybe **hvac_action** vs **hvac_modes**

His Stacktrace points out the attribute hvac_modes, your code requires havac_action

**Comment by joBr99** [comment]
this check is new with 1.2.2 which prevents the errorin the stacktrace

```
    status       = ""
    if "hvac_action" in entity.attributes:
      status = entity.attributes.hvac_action
```

**Comment by najjadasm** [comment]
![Screenshot_20220313-234424_Home Assistant](https://user-images.githubusercontent.com/60378456/158078502-5f97321e-118f-415f-af99-271c67d10e1c.jpg)
 myapp is 1.2.2

what can do to solve the problem?

**Comment by joBr99** [comment]
try to redownload, check the python script it should look like this around line 373

![image](https://user-images.githubusercontent.com/29555657/158078720-0cdd3ce5-610b-4926-9032-8ab6c074311a.png)

if your script is the same as one the screenshot, try to restart appdaemon

**Comment by najjadasm** [comment]
script is the same as one the screenshot,
I restarted appdaemon and still the same 

I appreciate your support

**Comment by joBr99** [comment]
do you still get the warning in your log?

**Comment by najjadasm** [comment]
yes

**Comment by joBr99** [comment]
still this error in the exact same line? this doesn't make any sense

`AttributeError: 'AttrDict' object has no attribute 'hvac_action'status = entity.attributes.hvac_actionFile "/config/appdaemon/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py", line 373`

**Comment by najjadasm** [comment]
pDaemon v4.2.1
Logs
Log
error_log
Search
bed
2022-03-14 00:44:19.086736 WARNING nspanel: Worker Ags: {'id': '409baa0340a64caf94b5a2b80c0c69a0', 'name': 'nspanel', 'objectid': 'eabc31257a394428a8d7e143e0b83df3', 'type': 'state', 'function': <bound method NsPanelLovelaceUI.state_change_callback of <nspanel-lovelace-ui.NsPanelLovelaceUI object at 0x7f26465276a0>>, 'attribute': 'all', 'entity': 'climate.bed_rm_ac', 'new_state': {'entity_id': 'climate.bed_rm_ac', 'state': 'off', 'attributes': {'hvac_modes': ['off', 'cool', 'dry', 'fan_only'], 'min_temp': 18.0, 'max_temp': 30.0, 'target_temp_step': 1.0, 'fan_modes': ['auto', 'low', 'medium', 'high'], 'current_temperature': None, 'temperature': 23, 'current_humidity': 36.53, 'fan_mode': 'low', 'last_on_operation': 'cool', 'device_code': 1318, 'manufacturer': 'Fujitsu', 'supported_models': ['AR-AB5'], 'supported_controller': 'Broadlink', 'commands_encoding': 'Base64', 'friendly_name': 'Bed Room AC', 'supported_features': 9}, 'last_changed': '2022-03-13T14:25:53.896344+00:00', 'last_updated': '2022-03-13T21:44:19.034894+00:00', 'context': {'id': 'ef36c2957e57a652780262b4c7d48511', 'parent_id': None, 'user_id': None}}, 'old_state': {'entity_id': 'climate.bed_rm_ac', 'state': 'off', 'attributes': {'hvac_modes': ['off', 'cool', 'dry', 'fan_only'], 'min_temp': 18.0, 'max_temp': 30.0, 'target_temp_step': 1.0, 'fan_modes': ['auto', 'low', 'medium', 'high'], 'current_temperature': None, 'temperature': 23, 'current_humidity': 35.63, 'fan_mode': 'low', 'last_on_operation': 'cool', 'device_code': 1318, 'manufacturer': 'Fujitsu', 'supported_models': ['AR-AB5'], 'supported_controller': 'Broadlink', 'commands_encoding': 'Base64', 'friendly_name': 'Bed Room AC', 'supported_features': 9}, 'last_changed': '2022-03-13T14:25:53.896344+00:00', 'last_updated': '2022-03-13T21:43:19.043053+00:00', 'context': {'id': 'fcee9a936b27373cc6f3497493447c32', 'parent_id': None, 'user_id': None}}, 'pin_app': True, 'pin_thread': 5, 'kwargs': {'attribute': 'all', '__thread_id': 'thread-5'}}

**Comment by joBr99** [comment]
it's not the same :) 

update your script to this version and try again

https://raw.githubusercontent.com/joBr99/nspanel-lovelace-ui/main/apps/nspanel-lovelace-ui/nspanel-lovelace-ui.py

**Comment by najjadasm** [comment]
Now it work after update the script for adjutant Temp only
 
I can't tune on or turn off the claimant or change the mode from nspanel

Thanks a lot for support

**Comment by najjadasm** [comment]
![16472342006081525052043984325804](https://user-images.githubusercontent.com/60378456/158108119-2dd57304-a2b2-4155-a422-288e565f56ef.jpg)

**Comment by joBr99** [comment]
Well changeing the cliemate modes is currently not possible, I added an issue for this feature request.

Is setting of the temperature itself working?

**Comment by joBr99** [comment]
I will need to add the icons to the display firmware, implement them in the serial protocol and I need to implement it in the python script.

**Comment by joBr99** [comment]
@najjadasm can you send me screenshots from each havc mode from the frontend?

I need it for the color's of the icons

![image](https://user-images.githubusercontent.com/29555657/158234413-a3346acc-30a2-4f30-8a82-b841e61a6602.png)

![image](https://user-images.githubusercontent.com/29555657/158234433-7cda35e2-5dfe-4764-88b7-3c3d3ded8ea0.png)

**Comment by najjadasm** [comment]
![Screenshot_20220314-214046_Home Assistant](https://user-images.githubusercontent.com/60378456/158239611-6de340cb-17e3-4dd9-84af-4aeb8ddbd921.jpg)
![Screenshot_20220314-214052_Home Assistant](https://user-images.githubusercontent.com/60378456/158239633-93125c2c-2117-47af-bdd2-1d9a420e6963.jpg)
![Screenshot_20220314-214058_Home Assistant](https://user-images.githubusercontent.com/60378456/158239648-10221306-70da-4117-8121-b7214e2851d5.jpg)
![Screenshot_20220314-214106_Home Assistant](https://user-images.githubusercontent.com/60378456/158239673-af1fb5ba-678e-4ddf-b268-4e230ed6320a.jpg)

**Comment by najjadasm** [comment]
I don't have heat mode in my HVAC unit

**Comment by najjadasm** [comment]
![Screenshot_20220315-005434_WhatsApp](https://user-images.githubusercontent.com/60378456/158267906-8c312a55-2c42-4ac1-a273-82cfc7a9ef75.jpg)

It is working fine but 
1  the cooling mode send as fan mode
2 fan mode icons missing and send as cooling mode

Thanks a lot for your support

**Comment by joBr99** [comment]
there should be a line in your log like this
`2022-03-14 23:01:15.868158 INFO nspanel-1: Send Message from Tasmota: entityUpd,climate.kuche_boden,Küche Boden,205,160,idle,150,250,5,,,,,,,,,,,,,,,,,,,,,,,,,28,64512,1,heat,27,35921,0,off,,,,`

can you send me this line?

**Comment by najjadasm** [comment]
2022-03-15 01:07:19.067203 INFO nspanel: Send Message from Tasmota: entityUpd,climate.living_room_ac,Living Room AC,246,210,,180,300,10,,,,,,,,,,,,,,,,,,,,,27,35921,0,off,31,11487,0,cool,26,60897,0,dry,30,35921,1,fan_only

**Comment by joBr99** [comment]
try to reflash the display firmware
should look like this now

![image](https://user-images.githubusercontent.com/29555657/158269465-1e515a0d-6c2a-416b-9239-593d9113d940.png)

**Comment by najjadasm** [comment]
![Screenshot_20220315-015208_WhatsApp](https://user-images.githubusercontent.com/60378456/158273755-bb860854-8aa6-4501-b9d2-935e69fb23bb.jpg)

Yes working fine after reflushing the firmware 

Thanks a lot
