### ISSUE TITLE
[BUG] cardQR entities problem

### ISSUE THREAD

**Issue by zanaca** [joBr99/nspanel-lovelace-ui#946]
### PROBLEM DESCRIPTION
Values from entities for cardQR are shown split if the origin is a `sensor` and not `iText`.  The values on qrCode as well is in fully form, but the written values are truncated

When using iText values, everything works as expected, but if the value is fetch from a sensor, they show only first four bytes

### REQUESTED INFORMATION

- [X] Provide your apps.yaml (or your config):
```
            - type: cardQR
              title: Guest WIFI
              qrCode: "WIFI:S:{{states('sensor.guest_wifi_ssid')}};T:WPA;P:{{states('sensor.guest_wifi_password')}};;"
              entities:
                  - entity: sensor.guest_wifi_ssid
                    #entity: iText.aLan Convidados
                    name: Rede
                    icon: wifi
                  - entity: sensor.guest_wifi_password
                    #entity: iText.v3rY%5ecR37
                    name: Senha
                    icon: key
```
* Note the "space" in SSID name, it works as *iText* and inside the *qrCode*.  The **commented** entity line does now exists really, are shown here just as example.

- [X] Go to Settings>Add-ons>AppDaemon>Log (or the output of your TS script) and then, provide the output of the log during your issue/bug occurs:
```
2023-07-31 11:39:06.040902 INFO nspanel-room1: Sending MQTT Message: pageType~cardQR
2023-07-31 11:39:06.057115 INFO nspanel-room1: Sending MQTT Message: timeout~20
2023-07-31 11:39:06.132060 INFO nspanel-room1: Sending MQTT Message: entityUpd~WiFi convidados~button~navigate.uuid.duMo1GVe8J~���~65535~unknown~Pressione~button~navigate.uuid.hjuOcCgpR8~���~65535~Escrit��rio~Pressione~WIFI:S:aLan Convidados;T:WPA;P:v3rY%5ecR37;;~text~sensor.guest_wifi_ssid~���~17299~Rede~aLan  ~text~sensor.guest_wifi_password~���~17299~Senha~v3rY 
```
* The logs from docker container probably does not handle utf-8 well

### TO REPRODUCE
- Define a SSID with space with more than 6 characters as a HA sensor
- Define a password as HA sensor
- Use those sensors as source from cardQR  entitities

### EXPECTED BEHAVIOUR
The shown text entities should be `aLan Convidados` for *Rede*  entity and `v3rY%5ecR37` for *Senha*  entity.

### SCREENSHOTS
_If applicable, add screenshots/pictures to help explain your problem._

### ADDITIONAL CONTEXT
As log shows, the "compiled" content are `aLan ` for *Rede* and `v3rY` for *Senha*, just for the written "entities". The qrCode is OK.

### PANEL / FIRMWARE VERION
Last version from US-P

**Comment by joBr99** [comment]
please update to the development version, I don't have this issue so I think it is already fixed

https://docs.nspanel.pky.eu/faq/#how-to-upgrade-from-a-release-to-the-current-development-version

![image](https://github.com/joBr99/nspanel-lovelace-ui/assets/29555657/1ad930dd-0c87-49ed-bd04-8ee8d4af0aa7)

**Comment by zanaca** [comment]
I have just updated to the last oficial release I can confirm the error still happening.

I am attaching new  pictures to help clarify the problem. I have updated the values to help "counting" the strings, the sensor values are really the values shown in the picture bellow
* Print from the sensor states
<img width="531" alt="image" src="https://github.com/joBr99/nspanel-lovelace-ui/assets/122560/b76a0524-09e8-4526-8293-2c512b39f375">

* apps.yaml (the nspannel only)
```yaml
nspanel-livingroom:
    module: nspanel-lovelace-ui
    class: NsPanelLovelaceUIManager
    config:
        panelRecvTopic: 'nspanel-livingroom/tele/RESULT'
        panelSendTopic: 'nspanel-livingroom/cmnd/CustomSend'
        updateMode: 'auto-notify'
        model: 'us-p'
        sleepTracking: True
        sleepTimeout: 20
        sleepBrightness:
            - time: 'sunrise + 1:00:00'
              value: 8
            - time: 'sunset'
              value: 1
        locale: 'pt_BR' # used for translations in translations.py and for localized date if babel python package is installed
        screensaver:
            entity: weather.forecast_home
            weatherOverrideForecast2:
                entity: sensor.nspanel_livingroom_analog_temperature1
                name: Ambiente
                icon: home-thermometer
            weatherOverrideForecast3:
                entity: sensor.climate_ar_sala_temperature
                name: Configurada
                icon: home-thermometer
            weatherOverrideForecast4:
                entity: climate.ar_sala
                name: Status
                icon: air-conditioner
            key: clima
            theme:
                autoWeather: true
                background: [0, 0, 0]
        cards:
            - type: cardGrid
              entities:
                  - entity: light.luz_sala
                    icon: lightbulb
                    name: Luz do teto
                  - entity: switch.ventilador
                    icon: fan
                    name: Ventilador
                  - entity: light.luz_do_corredor
                    name: Luz do corredor
                  - entity: light.luz_cozinha
                    name: Luz da cozinha
                  - entity: button.tv
                    name: TV
                    icon: mdi:television-classic
                    color: '{{iif(states("binary_sensor.tv_sala")=="on", "[255,255,0]", "[54,95,140]")}}'

              title: Sala
            - type: cardThermo
              entity: climate.ar_sala
              title: Ar condicionado
            - type: cardEntities
              title: Locomoção
              entities:
                  - entity: input_boolean.away_mode
                    name: Modo viagem
                    icon: beach
                  - entity: sensor.casa_para_itaborai
                    name: Ida Itaboraí
                    icon: car
                  - entity: sensor.casa_para_leblon
                    name: Ida p/ Leblon
                    icon: car
            - type: cardQR
              title: WiFi convidados
              qrCode: "WIFI:S:{{states('sensor.guest_wifi_ssid')}};T:WPA;P:{{states('sensor.guest_wifi_password')}};;"
              entities:
                  - name: Rede
                    entity: sensor.guest_wifi_ssid
                    icon: wifi
                  - entity: sensor.guest_wifi_password
                    name: Senha
                    icon: key
```
* Actual picture of the living room nspannel, showing the cut out values for the qrcode
![IMG_4055](https://github.com/joBr99/nspanel-lovelace-ui/assets/122560/d67cd8f1-8f2e-4a5f-98ec-8aa304516ece)
(if you scan the qrcode will see the actual values, the same from the first print, besides the "1234" version written on screen

For the record, I do have Babel installed for the l10n.

Thanks,

**Comment by zanaca** [comment]
After the steps above, I changed the values to "broken clouds" as you tested. Seeing the appdaemon I see the same  problem as before, strings are cut down.

```
2023-08-21 23:24:35.479211 INFO nspanel-livingroom: Sending MQTT Message: pageType~cardQR
2023-08-21 23:24:35.493080 INFO nspanel-livingroom: Sending MQTT Message: timeout~20
2023-08-21 23:24:36.137539 INFO nspanel-livingroom: Sending MQTT Message: entityUpd~WiFi convidados~button~navigate.uuid.H9oRUcokos~���~65535~Locomo����o~Pressione~button~navigate.uuid.CwVY20yltO~���~65535~unknown~Pressione~WIFI:S:broken clouds;T:WPA;P:broken clouds;;~text~sensor.guest_wifi_ssid~���~17299~Rede~brok ~text~sensor.guest_wifi_password~���~17299~Senha~brok
2023-08-21 23:24:55.809205 INFO nspanel-room2: MQTT callback for: {'topic': 'nspanel-livingroom/tele/RESULT', 'wildcard': None, 'payload': '{"CustomRecv":"event,sleepReached,cardQR"}'}
2023-08-21 23:24:55.816998 INFO nspanel-room2: Received Message from Screen: event,sleepReached,cardQR
```

And it print "brok" on screen.

**Comment by joBr99** [comment]
Please restart appdaemon and look for this message in the startup log:

```
2023-08-22 16:53:37.295918 INFO nspanel-kueche: Started (v4.2.0)
```

Either your files didn't update or you didn't restart appdaemon.

If the line says 4.2.0 please check if the bug is still there, otherwise check the version you have in `nspanel-lovelace-ui.py`.

**Comment by zanaca** [comment]
- Current appdaemon version:
`2023-08-23 00:02:08.005549 INFO nspanel-livingroom: Started (v4.2.0)`

- "Bug" still there:
  password and ssid as `brok`
  
- Version at line 31 of nspanel-lovelace-ui.py:
`        version     = "v4.2.0"`

- MD5 checksum of nspanel-lovelace-ui.py:
`md5sum nspanel-lovelace-ui.py` ->  97e9205339c9c9a26017a5d37e8809ad  nspanel-lovelace-ui.py

**Comment by zanaca** [comment]
Thats the "problem":
https://github.com/joBr99/nspanel-lovelace-ui/blob/main/apps/nspanel-lovelace-ui/luibackend/pages.py#L303

I have  removed the `[:4]` and now the string is full length

**Comment by joBr99** [comment]
o.O why did it work in my test with US-P a couple of weeks ago

Please try with this change:

~https://github.com/joBr99/nspanel-lovelace-ui/commit/cf1acdefffce23cb0839178f0a6c2a10fc365461~

https://github.com/joBr99/nspanel-lovelace-ui/commit/11106eb77817d035d6809bf7abd9b09d2a8ad00b


I cannot remember why this was added, but I guess to limit it on cardEntities, there is less space for sensors on us-p than on the landscape versions.
